apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-es-general-query
data:
  general_query.conf: |
    input {
      # Read all documents from Elasticsearch matching the given query
      elasticsearch {
        hosts => "elasticsearch-master:9200"
        index => "${INDEX}"
        query => '{
          "_source": "${SOURCE}",
          "query": {
            "query_string": {
              "query": "${QUERY}"
            }
          },
          "size": ${SIZE}
        }'
      }
    }
    output {

      file {
          path => "/tmp/result.txt"
          codec => line {
            format => "%{${FORMAT_SOURCE}}"
          }
      }
    }