apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-subdomain
data:
  subdomain.conf: |
    input {
      file {
        path => "/tmp/subdomains.txt"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        exit_after_read => true
        mode => "read"
        file_chunk_size => 3145728  # 3MB
      }
    }

    filter {
       csv {
        columns =>  ["host"]
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch-master:9200"]
        index => "subdomain"
        document_id => "%{host}"

        scripted_upsert => true
        action => "update"
        script_lang => "painless"
        script_type => "inline"
        script => "
          if(ctx.op == 'create') {
            ctx._source=params.event;
            ctx._source.first_create_time = params.event.get('@timestamp');
          } else {
            String old = ctx._source.get('first_create_time');
            for (entry in params.event.entrySet()) {
              ctx._source[entry.getKey()] = entry.getValue()
            }
            ctx._source.last_update_time = params.event.get('@timestamp');
            ctx._source.first_create_time = old;
          }
        "
      }
    }
