apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level1-get-subdomains
spec:
  volumes:
    - name: logstash-config-map
      configMap:
        name: logstash
  templates:
    - name: oneforall
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
      container:
        image: shmilylty/oneforall:version-0.4.3
        command:
          - sh
        args:
          - -c
          - python3 oneforall.py --target {{`{{inputs.parameters.domain}}`}} --dns false run && cat /OneForAll/results/{{`{{inputs.parameters.domain}}`}}.csv | awk -F ',' '{print $6}'|tail -n +2 |sort|uniq > /tmp/result

    - name: subfinder-no-save
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
      volumes:
        - name: config-nuclei
          configMap:
            name: config-nuclei
      script:
        volumeMounts:
          - name: config-nuclei
            mountPath: /root/.config/subfinder/
        image: 'projectdiscovery/subfinder:v2.5.5'
        command:
          - sh
        source: |
          subfinder -active -d {{`'{{inputs.parameters.domain}}'`}} -json -o /tmp/result

    - name: subfinder
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            from: {{`'{{steps.save.outputs.artifacts.result}}'`}}
      steps:
        - - name: subfinder-no-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            template: subfinder-no-save
        - - name: save
            arguments:
              artifacts:
                - name: subdomain-result
                  from: {{`'{{steps.subfinder-no-save.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: level1-logstash
              template: subfinder

    - name: get-subdomains-from-es
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
      container:
        image: 'leveryd/x-tool:v2023.1.16'
        command:
          - "x"
        args:
          - 'subdomain'
          - '-esURL'
          - 'http://elasticsearch-master:9200'  # elasticsearch-master 是es的服务名
          - '-domain'
          - {{`'{{inputs.parameters.domain}}'`}}
          - '-of'
          - '/tmp/result'

    - name: get-subdomain
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
            globalName: subdomains
      volumes:
        - name: workspace
          emptyDir: {}
      containerSet:
        volumeMounts:
          - mountPath: /tmp
            name: workspace
        containers:
          - name: oneforall
            image: shmilylty/oneforall:version-0.4.3
            command:
              - sh
            args:
              - "-c"
              - "echo {{`{{inputs.parameters.get-subdomain-way}}`}} | grep oneforall -i && python3 oneforall.py --target {{`{{inputs.parameters.domain}}`}} --dns false run && cat /OneForAll/results/{{`{{inputs.parameters.domain}}`}}.csv | awk -F ',' '{print $6}'|tail -n +2 |sort|uniq > /tmp/oneforall;exit 0"
            # when: "1==0" # it does not work
          - name: subfinder
            image: 'projectdiscovery/subfinder:v2.5.5'
            command:
              - sh
            args:
              - "-c"
              - "echo {{`{{inputs.parameters.get-subdomain-way}}`}} | grep subfinder -i && subfinder -d {{`'{{inputs.parameters.domain}}'`}} -o /tmp/subfinder;exit 0"
          - name: es
            image: 'leveryd/x-tool:v2023.1.16'
            command:
              - sh
            args:
              - "-c"
              - "echo {{`{{inputs.parameters.get-subdomain-way}}`}} | grep es -i && x subdomain -domain {{`'{{inputs.parameters.domain}}'`}} -esURL http://elasticsearch-master:9200 -of /tmp/es;exit 0"
          - name: mysql
            image: 'leveryd/x-tool:v2023.1.16'
            command:
              - sh
            args:
              - "-c"
              - "echo {{`{{inputs.parameters.get-subdomain-way}}`}} | grep mysql -i && x subdomain -domain {{`'{{inputs.parameters.domain}}'`}} -action get -source mysql -datasource 'root:{{.Values.console_db_root_password}}@tcp({{.Values.console_db_host}})/cute' -of /tmp/mysql;exit 0"

          - name: main
            image: ubuntu:lunar-20221207
            command:
              - sh
            args:
              - -c
              - "wc -l /tmp/* && cat /tmp/* | sort | uniq > /tmp/result && wc -l /tmp/result"
            dependencies:
              - subfinder
              - oneforall
              - es
              - mysql
