apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-asset-level1-fofa
spec:
  arguments:
    parameters:
      - name: fofa_key
        default: "{{.Values.fofa_key}}"
        description: "fofa key, can be specified when operator install asm instance"
      - name: fofa_email
        default: "{{.Values.fofa_email}}"
        description: "fofa email, can be specified when operator install asm instance"
      - name: query
        description: "fofa query, do not use single quotes"
      - name: size
        default: 10
        description: "number of results to return"
  templates:
    - name: fofa-client-no-save
      outputs:
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count.txt
        artifacts:
          - name: result
            description: "csv type"
            path: /tmp/result.txt
          - name: urls
            path: /tmp/urls.txt
          - name: hosts
            path: /tmp/hosts.txt
      script:
        image: busybox:glibc
        command: ["/bin/sh"]
        env:
          - name: FOFA_KEY
            value: {{`"{{workflow.parameters.fofa_key}}"`}}
          - name: FOFA_EMAIL
            value: {{`"{{workflow.parameters.fofa_email}}"`}}
        source: |
          cp /tmp/tools/fofax/fofax /bin/fofax
          fofax -disable-update -silent    # create config

          fofax -disable-update -q '{{`{{workflow.parameters.query}}`}}' -fs {{`{{workflow.parameters.size}}`}} -ff host,port,ip,lastupdatetime > /tmp/result.txt

          awk -F',' '{printf "%s:%s\n",$1,$2;}' /tmp/result.txt | sort | uniq > /tmp/urls.txt

          awk -F',' '{printf "%s,%s\n",$1,$4;}' /tmp/result.txt | sort | uniq > /tmp/hosts.txt
          sed /tmp/hosts.txt -i -e "s/http:\/\///g"
          sed /tmp/hosts.txt -i -e "s/https:\/\///g"

          wc -l /tmp/result.txt | awk '{print $1}' > /tmp/count.txt
        volumeMounts:
          - name: tools
            mountPath: /tmp/tools
      volumes:
        - name: tools
          persistentVolumeClaim:
            claimName: tools

    - name: fofa-client
      outputs:
        parameters:
          - name: count
            valueFrom:
              parameter: {{`"{{steps.call-fofa-client-no-save.outputs.parameters.count}}"`}}
        artifacts:
          - name: result
            description: "csv type"
            from:  {{`"{{steps.call-fofa-client-no-save.outputs.artifacts.result}}"`}}
          - name: urls
            from: {{`"{{steps.call-fofa-client-no-save.outputs.artifacts.urls}}"`}}
      steps:
        - - name: call-fofa-client-no-save
            template: fofa-client-no-save
        - - name: call-save-port
            arguments:
              artifacts:
                - name: port
                  from: {{`"{{steps.call-fofa-client-no-save.outputs.artifacts.result}}"`}}
                - name: subdomain
                  from: {{`"{{steps.call-fofa-client-no-save.outputs.artifacts.hosts}}"`}}
            templateRef:
              name: save-asset-level1-fofa-to-es
              template: fofa