apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-asset-level1-sld-domain-from-es
spec:
  templates:
    - name: from-es
      volumes:
        - name: logstash-config-sld
          configMap:
            name: logstash-config-sld
      inputs:
        parameters:
          - name: org
            description: "组织名"
      outputs:
        artifacts:
          - name: result
            path: /tmp/host.txt
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count.txt
      script:
        image: logstash:7.17.3
        command:
          - sh
        env:
          - name: ORG
            value: {{`"{{inputs.parameters.org}}"`}}
        source: |
          logstash --api.enabled false -w 1 --log.level error -f /tmp/logstash/sld.conf

          cat /tmp/host.txt | sort | uniq > /tmp/host.txt.tmp
          mv /tmp/host.txt.tmp /tmp/host.txt
          wc -l /tmp/host.txt | awk '{print $1}' > /tmp/count.txt
        volumeMounts:
          - name: logstash-config-sld
            mountPath: /tmp/logstash
