apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-probe-subdomain-from-response
spec:
  schedule: "*/10 * * * *"
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: probe-asset-level1-subdomain-from-response
    arguments:
      parameters:
        - name: q
          value: "timestamp:[now-11m TO now]"
    entrypoint: probe-subdomain-from-response
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-probe-subdomain-from-tls-subject
spec:
  schedule: "*/10 * * * *"
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: probe-asset-level1-subdomain-from-response
    arguments:
      parameters:
        - name: q
          value: "timestamp:[now-11m TO now]"
        - name: index
          value: "tls"
        - name: source
          value: "subject_an"
        - name: format_source
          value: "[subject_an]"
    entrypoint: probe-subdomain-from-response
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-probe-subdomain-from-tls-sni
spec:
  schedule: "*/10 * * * *"
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: probe-asset-level1-subdomain-from-response
    arguments:
      parameters:
        - name: q
          value: "timestamp:[now-11m TO now]"
        - name: index
          value: "tls"
        - name: source
          value: "sni"
        - name: format_source
          value: "[sni]"
    entrypoint: probe-subdomain-from-response
