apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-cidr
data:
  asn.conf: |
    input {
      # Read all documents from Elasticsearch matching the given query
      elasticsearch {
        hosts => "elasticsearch-master:9200"
        index => "web-service"
        query => '{
          "_source": "asn.as-range",
          "query": {
            "query_string": {
              "query": "INPUT_QUERY"
            }
          }
        }'
      }
    }
    output {
      file {
        path => "/tmp/json.txt"
        codec => json_lines
      }

      file {
          path => "/tmp/asn.txt"
          codec => line {
            format => "%{[asn][as-range]}"
          }
      }
    }
