apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-asset-level1-cidr
spec:
  volumes:
    - name: logstash-config-cidr
      configMap:
        name: logstash-config-cidr
  templates:
    - name: asn-range-from-es
      inputs:
        parameters:
          - name: q
            description: 'elasticsearch query, e.g. "*"'
            default: "*"
      outputs:
        artifacts:
          - name: result
            path: /tmp/asn.txt
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count.txt
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          cp /tmp/logstash/* /tmp/
          sed /tmp/asn.conf -i -e "s/INPUT_QUERY/{{`{{inputs.parameters.q}}`}}/g"
          logstash -f /tmp/asn.conf

          cat /tmp/asn.txt | sort | uniq > /tmp/asn.txt.tmp
          mv /tmp/asn.txt.tmp /tmp/asn.txt

          wc -l /tmp/asn.txt | awk '{print $1}' > /tmp/count.txt
        volumeMounts:
          - name: logstash-config-cidr
            mountPath: /tmp/logstash

    - name: aggregate-ip-from-es
      inputs:
        parameters:
          - name: q
            description: 'elasticsearch query, e.g. "*"'
            default: "*"
      outputs:
        artifacts:
          - name: result
            fromExpression: "steps.cidr.outputs.artifacts.result"
        parameters:
          - name: count
            valueFrom:
              expression: "steps.cidr.outputs.parameters.count"
      steps:
        - - name: get-ips
            arguments:
              parameters:
                - name: q
                  value: '{{`{{inputs.parameters.q}}`}}'
            templateRef:
              name: get-asset-level1-ip
              template: get-ip-from-es-by-query
        - - name: cidr    # name can not be "get-cidr", i don't know why
            arguments:
              artifacts:
                - name: compute-cidr-input
                  from: '{{`{{steps.get-ips.outputs.artifacts.result}}`}}'
            templateRef:
              name: util-asset
              template: compute-cidr-aggregate-approx

{{/*    - name: query*/}}
{{/*      inputs:*/}}
{{/*        parameters:*/}}
{{/*          - name: q*/}}
{{/*            description: 'elasticsearch query, e.g. "*"'*/}}
{{/*            default: "*"*/}}
{{/*      outputs:*/}}
{{/*        artifacts:*/}}
{{/*          - name: result*/}}
{{/*            path: /tmp/cidr.txt*/}}
{{/*        parameters:*/}}
{{/*          - name: count*/}}
{{/*            valueFrom:*/}}
{{/*              path: /tmp/count.txt*/}}
{{/*      script:*/}}
{{/*        image: leveryd/x-tool:v2023.1.16*/}}
{{/*        command:*/}}
{{/*          - 'sh'*/}}
{{/*        source: |*/}}
{{/*          x es -esURL http://elasticsearch-master:9200 -index web-service -num 10000 -q '{{`{{inputs.parameters.q}}`}}' -source "asn.as-number" -of /tmp/cidr.txt*/}}
{{/*          wc -l /tmp/cidr.txt | awk '{print $1}' > /tmp/count.txt*/}}