apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: util-es-client
spec:
  templates:
    - name: es-client
      inputs:
        parameters:
          - name: q
            description: Query to search for
            default: "*"
          - name: index
            description: Index to search
            default: "web-service"
          - name: field
            description: Field to search
            default: "url"
      outputs:
        artifacts:
          - name: result
            path: /tmp/result
      script:
        image: leveryd/x-tool:v2023.1.16
        command:
          - 'sh'
        source: |
          x es -esURL http://elasticsearch-master:9200 -index {{`{{inputs.parameters.index}}`}} -num 10000 -q '{{`{{inputs.parameters.q}}`}}' -source {{`{{inputs.parameters.field}}`}} -of /tmp/result