apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: level2-domain-nuclei
spec:
  templates:
    - name: 获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain
      steps:
        - - name: call-get-subdomains
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: level1-get-subdomains
              template: subfinder
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-get-subdomains.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: level1-nuclei
              template: nuclei-scan
        - - name: call-save-nuclei-alarm
            arguments:
              artifacts:
                - from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
                  name: result
            templateRef:
              name: level1-save-alarm
              template: save-nuclei

    - name: oneforall获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain
            description: "二级域名，比如 baidu.com"
      steps:
        - - name: call-get-subdomains
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: level1-get-subdomains
              template: oneforall
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-get-subdomains.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: level1-nuclei
              template: nuclei-scan
        - - name: call-save-nuclei-alarm
            arguments:
              artifacts:
                - from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
                  name: result
            templateRef:
              name: level1-save-alarm
              template: save-nuclei

    - name: nuclei扫描-保存结果    # 测试nuclei扫描后保存扫描结果
      inputs:
        parameters:
          - name: domain
            description: "域名，比如 www.baidu.com"
      steps:
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  raw:
                    data: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: level1-nuclei
              template: nuclei-scan
        - - name: save-nuclei
            arguments:
              artifacts:
                - name: result
                  from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
            templateRef:
              name: level1-save-alarm
              template: save-nuclei

  podGC:
    strategy: OnPodCompletion
  ttlStrategy:
    secondsAfterCompletion: 300
