apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level1-httpx
spec:
  arguments: {}
  templates:
    - name: probe-80-443-from-file  # 只被katana调用
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/hosts
      outputs:
        artifacts:
          - name: urls
            path: /tmp/result
      container:
        image: projectdiscovery/httpx:v1.2.4
        command:
          - 'sh'
        args:
          - "-c"
          - "httpx -l /tmp/hosts -p http:80,https:443 -fc 404,403,500,301,302 -ct -o /tmp/1 && grep -i html /tmp/1 | awk '{print $1}' > /tmp/result"

    - name: probe-from-file
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/hosts
        parameters:
          - name: port-range
            value: "http:80,https:443"
      outputs:
        artifacts:
          - name: urls
            path: /tmp/result
      container:
        image: projectdiscovery/httpx:v1.2.4
        command:
          - 'sh'
        args:
          - "-c"
          - "httpx -l /tmp/hosts -p {{`{{inputs.parameters.port-range}}`}} -fc 404,403,500 -ct -o /tmp/1 && grep -i html /tmp/1 | awk '{print $1}' > /tmp/result"

    - name: probe-from-file-no-port
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/hosts
      outputs:
        artifacts:
          - name: urls
            path: /tmp/result
      container:
        image: projectdiscovery/httpx:v1.2.4
        command:
          - 'sh'
        args:
          - "-c"
          - "httpx -l /tmp/hosts -ec -o /tmp/result"

    - name: probe-all-from-file-no-port
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/hosts
      outputs:
        artifacts:
          - name: urls
            path: /tmp/result
      container:
        image: projectdiscovery/httpx:v1.2.4
        command:
          - 'sh'
        args:
          - "-c"
          - "httpx -fc 0 -l /tmp/hosts -sc -cl -ct -location -lc -wc -rt -title -server -td -ip -cname -asn -cdn -probe -json -ec -o /tmp/result"

    - name: probe-favicon-from-urlfile
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/hosts
      outputs:
        artifacts:
          - name: result
            path: /tmp/favicon.txt
      container:
        image: projectdiscovery/httpx:v1.2.7
        command:
          - 'sh'
        args:
          - "-c"
          - "httpx -fc 0 -l /tmp/hosts -sc -probe -irrb -ec -path favicon.ico -json -o /tmp/favicon.txt"
