apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level1-naabu
spec:
  templates:
    - name: port-scan
      inputs:
        artifacts:
          - name: hosts
        parameters:
          - name: port-range
            default: "8000-9000"
      outputs:
        artifacts:
          - name: result   # every line in the result file will be like "host:port"
            from: {{`"{{steps.result-to-es.outputs.artifacts.result}}"`}}
      steps:
        - - name: naabu
            arguments:
              parameters:
                - name: port-range
                  value: {{`"{{inputs.parameters.port-range}}"`}}
              artifacts:
                - name: hosts
                  from: {{`"{{inputs.artifacts.hosts}}"`}}
            template: port-scan-no-save
        - - name: result-to-es
            arguments:
              artifacts:
                - name: port-result
                  from: {{`"{{steps.naabu.outputs.artifacts.result}}"`}}
            templateRef:
              name: level1-logstash
              template: probe-port

    - name: port-scan-no-save
      retryStrategy: # because '-ec' options maybe fail
        limit: "3"
        retryPolicy: "Always"
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/hosts
        parameters:
          - name: port-range
            value: "8000-9000"
      outputs:
        artifacts:
          - name: result   # every line in the result file will be like "host:port"
            path: /tmp/result
      script:
        image: projectdiscovery/naabu:v2.1.1
        command:
          - 'sh'
        source: |
          naabu -l /tmp/hosts -r 114.114.114.114,8.8.8.8 -ec -stats -p {{`{{inputs.parameters.port-range}}`}} -json -o /tmp/result
