{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: RoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: artifactgc-default*/}}
{{/*roleRef:*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}
{{/*  kind: Role*/}}
{{/*  name: artifactgc*/}}
{{/*subjects:*/}}
{{/*  - kind: ServiceAccount*/}}
{{/*    name: default*/}}
{{/*---*/}}
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: RoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: executor-default*/}}
{{/*roleRef:*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}
{{/*  kind: Role*/}}
{{/*  name: executor*/}}
{{/*subjects:*/}}
{{/*  - kind: ServiceAccount*/}}
{{/*    name: default*/}}
{{/*---*/}}
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: RoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: pod-manager-default*/}}
{{/*roleRef:*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}
{{/*  kind: Role*/}}
{{/*  name: pod-manager*/}}
{{/*subjects:*/}}
{{/*  - kind: ServiceAccount*/}}
{{/*    name: default*/}}
{{/*---*/}}
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: RoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: workflow-manager-default*/}}
{{/*roleRef:*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}
{{/*  kind: Role*/}}
{{/*  name: workflow-manager*/}}
{{/*subjects:*/}}
{{/*  - kind: ServiceAccount*/}}
{{/*    name: default*/}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
---