apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-crawl-scan
spec:
  # run everyd two days
  schedule: "0 0 */2 * *"
  concurrencyPolicy: Forbid  # do not allow any new while there are old
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: level3-crawl-scan
    arguments:
      parameters:
        - name: query
          value: 'limit=10000&offset=0&accurate=是'
    entrypoint: 从API获取兄弟域名-从ES获取web服务-katana爬虫-xray扫描-保存结果
