apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level2-es-nuclei
spec:
  templates:
    - name: es查询webservice获取url列表-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: q
            description: 'elasticsearch query, e.g. "*"'
            default: "*"
      steps:
        - - name: call-url-from-es
            arguments:
              parameters:
                - name: q
                  value: {{`'{{inputs.parameters.q}}'`}}
            templateRef:
              name: get-asset-level1-url
              template: url-from-es
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-url-from-es.outputs.artifacts.result}}'`}}
            templateRef:
              name: level1-nuclei
              template: nuclei-scan
        - - name: call-save-nuclei-alarm
            arguments:
              artifacts:
                - from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
                  name: result
            templateRef:
              name: level1-save-alarm
              template: save-nuclei