apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-url
data:
  url.conf: |
    input {
      # Read all documents from Elasticsearch matching the given query
      elasticsearch {
        hosts => "elasticsearch-master:9200"
        index => "web-service"
        query => '{
          "_source": "url",
          "query": {
            "query_string": {
              "query": "${QUERY}"
            }
          }
        }'
      }
    }

    output {
      file {
          path => "/tmp/url.txt"
          codec => line {
            format => "%{url}"
          }
      }
    }
