apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
spec:
  rules:
    - host: kibana.{{.Values.console_domain}}
      http:
        paths:
          - path: / # match all paths that begin with /argo/
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-kibana   # name of the service
                port:
                  number: 5601
