apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-probe-web-service
spec:
  # run every two days
  schedule: "0 0 */2 * *"
  concurrencyPolicy: Forbid  # do not allow any new while there are old
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: level3-probe-web-service
    arguments:
      parameters:
        - name: query
          value: 'limit=10000&offset=0&accurate=是'
        - name: get-subdomain-way
          value: 'mysql'
        - name: save-subdomain-result
          value: false
        - name: port-range
          value: '80,443,8000-9000'
    entrypoint: 从API获取兄弟域名-获取子域名-web服务扫描-保存结果
