apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: crawler
spec:
  templates:
    - name: katana-service-from-domains
      inputs:
        parameters:
          - name: domains
      outputs: {}
      script:
        image: python:3.8
        command:
          - python
        args:
          - '-u'
        source: |
          import json
          import sys
          import urllib.parse
          import urllib.request

          domains = {{`"""{{inputs.parameters.domains}}"""`}}

          url = 'http://crawler-service'  # todo:config
          for domain in domains.split("\n"):
            print("%s ok\n" % domain)
            domain = domain.strip()
            if domain != "":
              domain = "http://" + domain
              request=urllib.request.Request(url, domain.encode())
              reponse=urllib.request.urlopen(request).read()

          # json.dump(domains.split("\n"), sys.stdout)


    - name: katana-service-from-file
      inputs:
        artifacts:
          - name: domains
            path: /tmp/domains
      outputs: {}
      script:
        image: python:3.8
        command:
          - python
        args:
          - '-u'
        source: |
          import json
          import sys
          import urllib.parse
          import urllib.request

          domains = open("/tmp/domains", "r").read()

          url = 'http://crawler-service'  # todo:config
          for domain in domains.split("\n"):
            domain = domain.strip()
            print(domain)

            if domain != "":
              domain = "http://" + domain
              request=urllib.request.Request(url, domain.encode())
              reponse=urllib.request.urlopen(request).read()
              print("ok\n")

          # json.dump(domains.split("\n"), sys.stdout)

  ttlStrategy:
    secondsAfterCompletion: 3000
  podGC:
    strategy: OnPodCompletion
