apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: domains-poc-scan-template
spec:
  arguments:
    parameters:
      - name: xray-proxy-url
        value: "http://10.233.62.230:58088"
        description: "xray-proxy service address, e.g 'http://10.233.62.230:58088'"
  templates:
    - name: 获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain
      steps:
        - - name: call-get-subdomains
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: get-subdomains
              template: subfinder
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-get-subdomains.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: nuclei
              template: nuclei-scan
        - - name: call-save-nuclei-alarm
            arguments:
              artifacts:
                - from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
                  name: result
            templateRef:
              name: save-alarm
              template: save-nuclei

    - name: oneforall获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain
            description: "二级域名，比如 baidu.com"
      steps:
        - - name: call-get-subdomains
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: get-subdomains
              template: oneforall
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-get-subdomains.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: nuclei
              template: nuclei-scan
        - - name: call-save-nuclei-alarm
            arguments:
              artifacts:
                - from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
                  name: result
            templateRef:
              name: save-alarm
              template: save-nuclei

    - name: nuclei扫描-保存结果    # 测试nuclei扫描后保存扫描结果
      inputs:
        parameters:
          - name: domain
            description: "域名，比如 www.baidu.com"
      steps:
        - - name: call-nuclei-scan
            arguments:
              artifacts:
                - name: hosts
                  raw:
                    data: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: nuclei
              template: nuclei-scan
        - - name: save-nuclei
            arguments:
              artifacts:
                - name: result
                  from: {{`'{{steps.call-nuclei-scan.outputs.artifacts.nuclei-result}}'`}}
            templateRef:
              name: save-alarm
              template: save-nuclei

    - name: 获取子域名-katana爬虫-xray扫描-保存结果
      inputs:
        parameters:
          - name: domain
            description: "二级域名，比如 baidu.com"
      steps:
        - - name: call-subfinder
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: get-subdomains
              template: subfinder
        - - name: call-katana-service-from-file
            arguments:
              artifacts:
                - name: domains
                  from: {{`'{{steps.call-subfinder.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: crawler
              template: katana-service-from-file

    - name: 获取子域名-katana爬虫二进制-xray扫描-保存结果  # 区别：爬虫任务调用katana二进制，而不是katana服务
      inputs:
        parameters:
          - name: domain
            description: "二级域名，比如 baidu.com"
      steps:
        - - name: call-subfinder
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{inputs.parameters.domain}}'`}}
            templateRef:
              name: get-subdomains
              template: subfinder
        - - name: call-katana-binary
            arguments:
              artifacts:
                - name: domains
                  from: {{`'{{steps.call-subfinder.outputs.artifacts.subdomains}}'`}}
            templateRef:
              name: crawler
              template: katana-binary
  podGC:
    strategy: OnPodCompletion
  ttlStrategy:
    secondsAfterCompletion: 300
