apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: retest
spec:
  templates:
    - name: xray告警复测
      inputs:
        parameters:
          - name: url
          - name: plugin
      script:
        image: leveryd/xray:v2022.11.22
        command: [ "/bin/bash", "-c", "/tools/xray webscan --plugin {{`{{inputs.parameters.plugin}}`}} --url {{`{{inputs.parameters.url}}`}}"]
  ttlStrategy:
    secondsAfterCompletion: 3000
  podGC:
    strategy: OnPodCompletion
