apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retest
spec:
  templates:
    - name: xray告警复测
      inputs:
        parameters:
          - name: url
          - name: plugin
      script:
        image: leveryd/xray:v2023.2.21
        command: [ "/bin/bash", "-c", "/tools/xray webscan --plugin {{`{{inputs.parameters.plugin}}`}} --url {{`{{inputs.parameters.url}}`}}"]
