apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: util-update-nuclei-template
spec:
  volumes:
    - name: template-dir
      persistentVolumeClaim:
        claimName: nuclei-template

  templates:
    - name: update-nuclei-template
      inputs:
        parameters:
          - name: force-update
            default: false
      script:
        image: projectdiscovery/nuclei:v2.8.3
        command:
          - 'sh'
        source: |
          cd /root/nuclei-templates
          nuclei --target 127.0.0.1 -id CVE-2021-44228 -debug -ut

          if [ "{{`{{inputs.parameters.force-update}}`}}" = "true" ]
          then
            wget -c https://github.com/projectdiscovery/fuzzing-templates/archive/refs/tags/v0.0.2.zip -O /root/nuclei-templates/main.zip
            unzip /root/nuclei-templates/main.zip -d /root/nuclei-templates/
            rm -rf /root/nuclei-templates/main.zip
          fi

          ls -al /root/nuclei-templates
        volumeMounts:
          - name: template-dir
            mountPath: /root/nuclei-templates

    - name: lookup-nuclei-template
      script:
        image: projectdiscovery/nuclei:v2.8.3
        command:
          - 'sh'
        source: |
          tail -f /dev/null
        volumeMounts:
          - name: template-dir
            mountPath: /root/nuclei-templates