---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xray
    spec:
      containers:
        - name: proxy
          image: leveryd/xray:v2022.11.22
          ports:
            - containerPort: 80
          command: ["/bin/bash", "-c", "/tools/xray webscan --listen 0.0.0.0:80 --webhook-output http://{{.Values.xray_webhook_service}}:{{.Values.xray_webhook_port}}/webhook"]
        - name: webhook
          image: leveryd/xray-webhook:v2022.12.12
          imagePullPolicy: IfNotPresent
          env:
            - name: WEBHOOK_URL
              value: {{.Values.weixin_webhook_url}}
            - name: api
              value: "http://{{.Values.console_api_service_name}}:{{.Values.console_api_service_port}}"
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: xray
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.xray_proxy_service}}
spec:
  selector:
    app: xray
  ports:
    - protocol: TCP
      port: {{.Values.xray_proxy_port}}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.xray_webhook_service}}
spec:
  selector:
    app: xray
  ports:
    - protocol: TCP
      port: {{.Values.xray_webhook_port}}
      targetPort: 8080
