apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: probe-asset-level2-webservice-from-fofa
spec:
  arguments:
    parameters:
      - name: fofa_key
        default: "{{.Values.fofa_key}}"
        description: "fofa key, can be specified when operator install asm instance"
      - name: fofa_email
        default: "{{.Values.fofa_email}}"
        description: "fofa email, can be specified when operator install asm instance"
      - name: query
        description: "fofa query, do not use single quotes"
        default: 'host=".apple.com"'
      - name: size
        default: 10
        description: "number of results to return"
  templates:
    - name: fofa
      outputs:
        parameters:
          - name: count
            valueFrom:
              parameter: {{`"{{steps.call-fofa.outputs.parameters.count}}"`}}
        artifacts:
          - name: result
            description: "csv type"
            from: {{`"{{steps.call-fofa.outputs.artifacts.result}}"`}}
          - name: urls
            from: {{`'{{steps.call-httpx-scan.outputs.artifacts.urls}}'`}}
      steps:
        - - name: call-fofa
            templateRef:
              name: get-asset-level1-fofa
              template: fofa-client
        - - name: call-httpx-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-fofa.outputs.artifacts.urls}}'`}}
            templateRef:
              name: level1-httpx
              template: probe-all-from-file-no-port
        - - name: logstash
            arguments:
              artifacts:
                - name: httpx-result
                  from: {{`'{{steps.call-httpx-scan.outputs.artifacts.urls}}'`}}
            templateRef:
              name: level1-logstash
              template: httpx2elasticsearch