# probe web service status for ip segment
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level2-probe-web-service-from-ip-segment
spec:
  arguments:
    parameters:
      - name: passive
        description: "passive mode (default: false)"
        default: "false"
        enum:
          - "true"
          - "false"
  volumes:
    - name: logstash-config-map
      configMap:
        name: logstash
    - name: logstash-config-cidr
      configMap:
        name: logstash-config-cidr
  templates:
    - name: 根据cidr获取ip列表-端口扫描-存储结果
      inputs:
        parameters:
          - name: cidr
            description: "CIDR to map, eg 173.0.84.0/24"
          - name: port-range
            value: "80,443,8000-9000"
      steps:
        - - name: call-util-mapcidr
            arguments:
              parameters:
                - name: cidr
                  value: {{`'{{inputs.parameters.cidr}}'`}}
            templateRef:
              name: util-asset
              template: mapcidr
        - - name: call-port-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-util-mapcidr.outputs.artifacts.ip-result}}'`}}
              parameters:
                - name: port-range
                  value: {{`'{{inputs.parameters.port-range}}'`}}
            templateRef:
              name: probe-asset-level1-port
              template: port-scan
        - - name: call-httpx-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-port-scan.outputs.artifacts.result}}'`}}
            templateRef:
              name: level1-httpx
              template: probe-all-from-file-no-port
        - - name: logstash
            arguments:
              artifacts:
                - name: httpx-result
                  from: {{`'{{steps.call-httpx-scan.outputs.artifacts.urls}}'`}}
            templateRef:
              name: level1-logstash
              template: httpx2elasticsearch

    - name: 根据cidr文件获取ip列表-端口扫描-存储结果
      inputs:
        artifacts:
          - name: cidr
        parameters:
          - name: port-range
            value: "80,443,8000-9000"
      steps:
        - - name: call-util-mapcidr
            arguments:
              artifacts:
                - name: cidr
                  from: {{`'{{inputs.artifacts.cidr}}'`}}
            templateRef:
              name: util-asset
              template: mapcidr-from-file
        - - name: call-port-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-util-mapcidr.outputs.artifacts.ip-result}}'`}}
              parameters:
                - name: port-range
                  value: {{`'{{inputs.parameters.port-range}}'`}}
            templateRef:
              name: probe-asset-level1-port
              template: port-scan
        - - name: call-httpx-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`'{{steps.call-port-scan.outputs.artifacts.result}}'`}}
            templateRef:
              name: level1-httpx
              template: probe-all-from-file-no-port
        - - name: logstash
            arguments:
              artifacts:
                - name: httpx-result
                  from: {{`'{{steps.call-httpx-scan.outputs.artifacts.urls}}'`}}
            templateRef:
              name: level1-logstash
              template: httpx2elasticsearch