# probe web service status for ip segment
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: probe-asset-level2-web-service-from-es-subdomain
spec:
  arguments:
    parameters:
      - name: q
        description: 'elasticsearch query, e.g. "*"'
        default: "host:apple.com"
      - name: index
        default: "subdomain"
      - name: size
        default: "10000000"
      - name: source
        description: field to return
        default: "host"
      - name: format_source
        description: logstash field reference format, eg "[asn][as-range]"
        default: "[host]"
      - name: passive
        description: "passive mode when get port (default: false)"
        default: "false"
        enum:
          - "true"
          - "false"
      - name: port-range
        default: "80,443,8000-9000"
  volumes:
    - name: logstash-config-map
      configMap:
        name: logstash
  templates:
    - name: 根据查询获取主机端口信息-收集首页信息-存储结果
      steps:
        - - name: call-url-from-es
            templateRef:
              name: util-asset-es-query
              template: query-es
        - - name: call-port-scan
            arguments:
              artifacts:
                - name: hosts
                  from: {{`"{{steps.call-url-from-es.outputs.artifacts.result}}"`}}
              parameters:
                - name: port-range
                  value: {{`"{{workflow.parameters.port-range}}"`}}
            templateRef:
              name: probe-asset-level2-web-service
              template: from-host-file