---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: browserless
    spec:
      containers:
        - name: chrome
          image: browserless/chrome:1.57-puppeteer-13.1.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "1"
  selector:
    matchLabels:
      app: browserless
---
apiVersion: v1
kind: Service
metadata:
  name: browserless-service
spec:
  selector:
    app: browserless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
