apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level1-logstash
spec:
  templates:
    - name: httpx2elasticsearch
      volumes:
        - name: logstash-config-map
          configMap:
            name: logstash
      inputs:
        artifacts:
          - name: httpx-result
            path: /tmp/httpx-result.txt
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          logstash -f /tmp/logstash/httpx.conf
        volumeMounts:
          - name: logstash-config-map
            mountPath: /tmp/logstash

    - name: httpx-probe-favicon
      volumes:
        - name: logstash-config-map
          configMap:
            name: logstash
      inputs:
        artifacts:
          - name: httpx-result
            path: /tmp/httpx-result.txt
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          logstash -f /tmp/logstash/probe_favicon.conf
        volumeMounts:
          - name: logstash-config-map
            mountPath: /tmp/logstash

    - name: probe-tls
      volumes:
        - name: logstash-config-map
          configMap:
            name: logstash
      inputs:
        artifacts:
          - name: tls-result
            path: /tmp/tls-result.txt
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          logstash -f /tmp/logstash/probe_tls.conf
        volumeMounts:
          - name: logstash-config-map
            mountPath: /tmp/logstash

    - name: probe-port
      volumes:
        - name: logstash-config-map
          configMap:
            name: logstash
      inputs:
        artifacts:
          - name: port-result
            path: /tmp/port-result.txt
      outputs:
        artifacts:
          - name: result
            path: /tmp/url.txt
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          logstash -f /tmp/logstash/probe_port.conf
        volumeMounts:
          - name: logstash-config-map
            mountPath: /tmp/logstash

    - name: subfinder
      volumes:
        - name: logstash-config-map
          configMap:
            name: logstash
      inputs:
        artifacts:
          - name: subdomain-result
            path: /tmp/subdomain-result.txt
      outputs:
        artifacts:
          - name: result
            path: /tmp/subdomain.txt
      script:
        image: logstash:7.17.3
        command:
          - 'sh'
        source: |
          logstash -f /tmp/logstash/subfinder.conf
        volumeMounts:
          - name: logstash-config-map
            mountPath: /tmp/logstash