---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console-api
          image: leveryd/console-api:2022.12.9
          args:
            - -f
            - /etc/console/console-api.yaml
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATASOURCE
              value: root:{{.Values.console_db_root_password}}@tcp({{.Values.console_db_host}})/cute
          volumeMounts:
            - name: console-api-conf
              mountPath: /etc/console
          livenessProbe:
            periodSeconds: 5
            httpGet:
              path: /api/alarm/bbscan/query?limit=1
              port: 8080
        - name: console-fe
          image: leveryd/console-fe:2022.12.27
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      volumes:
        - name: console-api-conf
          configMap:
            name: console-api-conf
  selector:
    matchLabels:
      app: console
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.console_api_service_name}}
spec:
  selector:
    app: console
  ports:
    - protocol: TCP
      port: {{.Values.console_api_service_port}}
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: console-fe-service
spec:
  selector:
    app: console
  ports:
    - protocol: TCP
      port: 65533
      targetPort: 80
