apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: level1-identify-ms
spec:
  arguments: {}
  templates:
    - name: level1-identify-ms-from-url-file
      inputs:
        artifacts:
          - name: urls
            path: /tmp/urls.txt
      outputs:
        artifacts:
          - name: result
            path: /tmp/result
      container:
        image: 'leveryd/x-tool:v2023.1.16'
        args:
          - 'ims'
          - '-if'
          - '/tmp/urls.txt '
          - '-of'
          - '/tmp/result'

    - name: level1-identify-ms-from-one-url
      inputs:
        parameters:
          - name: url
            description: 'url eg. https://www.baidu.com'
      outputs:
        artifacts:
          - name: result
            path: /tmp/result
      container:
        image: 'leveryd/x-tool:v2023.1.16'
        args:
          - 'ims'
          - '-u'
          - {{`'{{inputs.parameters.url}}'`}}
          - '-of'
          - '/tmp/result'

  ttlStrategy:
    secondsAfterCompletion: 3000
  podGC:
    strategy: OnPodCompletion
