apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level1-nuclei
spec:
  arguments: {}
  templates:
    - name: retest  # 对报警复测
      inputs:
        parameters:
          - name: domain
            description: '域名列表，比如 apple.com<换行>twitter.com'
          - name: id
            description: 'nuclei 规则id'
      container:
        image: projectdiscovery/nuclei:v2.8.3
        command:
          - sh
        args:
          - -c
          - |
            echo {{`'{{inputs.parameters.domain}}'`}} | nuclei -id {{`'{{inputs.parameters.id}}'`}} -debug -duc {{include "interactsh_server" .}}
        volumeMounts:
          - name: template-dir
            mountPath: /root/nuclei-templates
      volumes:
        - name: template-dir
          persistentVolumeClaim:
            claimName: nuclei-template
      retryStrategy:
        limit: "3"
        retryPolicy: "Always"

    - name: nuclei-scan
      inputs:
        artifacts:
          - name: hosts
            path: /tmp/host
      outputs:
        artifacts:
          - name: nuclei-result
            path: /tmp/nuclei-result.json
      container:
        image: 'projectdiscovery/nuclei:v2.8.3'
        command:
          - nuclei
        args:
          - '-stats'
          - '-duc'
          - '-l'
          - /tmp/host
          - '-t'
          - >-
            exposures,misconfiguration,cnvd,vulnerabilities,workflows,exposed-panels
          - '-es'
          - info
          {{ if .Values.interactsh_server }}
          - '-iserver'
          - '{{ .Values.interactsh_server }}'
          {{ else }}
          - '-ni'
          {{ end }}
          - '-o'
          - /tmp/nuclei-result.json
        volumeMounts:
          - name: template-dir
            mountPath: /root/nuclei-templates
      volumes:
        - name: template-dir
          persistentVolumeClaim:
            claimName: nuclei-template
