apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: level1-get-subdomains
spec:
  templates:
    - name: oneforall
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
      container:
        image: shmilylty/oneforall:version-0.4.3
        command:
          - sh
        args:
          - -c
          - python3 oneforall.py --target {{`{{inputs.parameters.domain}}`}} --dns false run && cat /OneForAll/results/{{`{{inputs.parameters.domain}}`}}.csv | awk -F ',' '{print $6}'|tail -n +2 |sort|uniq > /tmp/result

    - name: subfinder
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
      container:
        image: 'projectdiscovery/subfinder:v2.5.5'
        args:
          - '-d'
          - {{`'{{inputs.parameters.domain}}'`}}
          - '-o'
          - '/tmp/result'

    - name: get-subdomains-from-es
      inputs:
        parameters:
          - name: domain
            description: '域名，比如 apple.com'
      outputs:
        artifacts:
          - name: subdomains
            path: /tmp/result
      container:
        image: 'leveryd/x-tool:v2023.1.16'
        args:
          - 'subdomain'
          - '-esURL'
          - 'http://elasticsearch-master:9200'  # elasticsearch-master 是es的服务名
          - '-domain'
          - {{`'{{inputs.parameters.domain}}'`}}
          - '-of'
          - '/tmp/result'

  ttlStrategy:
    secondsAfterCompletion: 3000
  podGC:
    strategy: OnPodCompletion
