apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: util-asset
spec:
  templates:
    - name: mapcidr
      inputs:
        parameters:
          - name: cidr
            description: "CIDR to map, eg 173.0.84.0/24"
      outputs:
        artifacts:
          - name: ip-result
            path: /tmp/cidr.txt
      script:
        image: projectdiscovery/mapcidr:v1.0.3
        command:
          - "/bin/sh"
        source: |
            mapcidr -cidr {{`{{inputs.parameters.cidr}}`}} -skip-base -skip-broadcast -silent -o /tmp/cidr.txt
            cat /tmp/cidr.txt

    - name: compute-cidr-aggregate-approx
      inputs:
        artifacts:
          - name: compute-cidr-input
            path: /tmp/cidr.txt
            description: "Aggregate sparse IPs/CIDRs into minimum approximated subnet"
      outputs:
        artifacts:
          - name: result
            path: /tmp/cidr.txt
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count.txt
      script:
        image: projectdiscovery/mapcidr:v1.0.3
        command:
          - "/bin/sh"
        source: |
          mapcidr -cidr /tmp/cidr.txt -aa -o /tmp/cidr.txt
          cat /tmp/cidr.txt
          wc -l /tmp/cidr.txt | awk '{print $1}' > /tmp/count.txt