apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-proxy-ca
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIEMDCCAxigAwIBAgIRAKdzpO/SuXtHA38AdG9Oi64wDQYJKoZIhvcNAQELBQAw
    gaExCzAJBgNVBAYTAkNOMRAwDgYDVQQHEwdCZWlqaW5nMRAwDgYDVQQJEwdCZWlq
    aW5nMRUwEwYDVQQKEwxDaGFpdGluIFRlY2gxKjAoBgNVBAsTIVNlcnZpY2UgSW5m
    cmFzdHJ1Y3R1cmUgRGVwYXJ0bWVudDErMCkGA1UEAxMiSW5zZWN1cmUgUm9vdCBD
    QSBGb3IgWC1SYXkgU2Nhbm5lcjAeFw0yMjExMjExNDU4MjJaFw0zMjExMTgxNDU4
    MjJaMIGhMQswCQYDVQQGEwJDTjEQMA4GA1UEBxMHQmVpamluZzEQMA4GA1UECRMH
    QmVpamluZzEVMBMGA1UEChMMQ2hhaXRpbiBUZWNoMSowKAYDVQQLEyFTZXJ2aWNl
    IEluZnJhc3RydWN0dXJlIERlcGFydG1lbnQxKzApBgNVBAMTIkluc2VjdXJlIFJv
    b3QgQ0EgRm9yIFgtUmF5IFNjYW5uZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQDBFN81fUsC5X2dPBJO2ks7c6tgX/390uJUN5kqZMh74YPBj5yLTMtQ
    3DEB2yPdsW6JqlEMvO5AAkD1YXIK3rgyZLFSRpPZeIQBGACZ5DrerzhL3XOwzig7
    wO/78DnF0J5d+tfIKYAVOWQX28R347xTPBf35gtvK0ALNhgDJKJ4o1LHZyIf+Uu0
    cjnBI9GwI/I9TZNxyZrezH2nWaCh7yz1mrGiD8aEyrXRihfr1AqrYJVkgR2PPYbf
    O9CrSrek91XuZG30rVk4rhFImahVTEN3pVW1zDl6Lz5dXcktPHZ0QhYJJiEUQNtR
    vtzW+3U1PzMs12Dnk9NGEYbXu+Ok1VhlAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwIC
    hDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUoIxVkHzjXYX8mrQ4/KyUFbx3cFgwDQYJKoZIhvcNAQELBQAD
    ggEBADWq+3md0U/1YiqXm/O32hZtuzQn/fIhmvY9KubIycKDc/h3GwsKDCZiYYYZ
    ZHIbrv33GUf0c+r+x62mRm4mcGMYosjw5bg7qg1/ixOnY7EGzK8IIO5T7YvsWxiN
    u/GIglebB2MDspzkUQx4Gw0Z20SC0yIt0thOR8PCis3HSPtYNN/RvD2Q6jwTQL4o
    99BlgnHopSWUVrLP8dYACVi819Dj/ULY5rXeX9hCwDJKy0AENmWe1VKCJYExjjQP
    TaFMffAgFHpEoZ6R5SSvvuTt7mBKOJ2HtIdhjE8bUlTnV5UYQpwzh9X9hi3YnWR7
    Px06xn6gRyLJBw0Th1f0RlT2W8s=
    -----END CERTIFICATE-----
  ca.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwRTfNX1LAuV9nTwSTtpLO3OrYF/9/dLiVDeZKmTIe+GDwY+c
    i0zLUNwxAdsj3bFuiapRDLzuQAJA9WFyCt64MmSxUkaT2XiEARgAmeQ63q84S91z
    sM4oO8Dv+/A5xdCeXfrXyCmAFTlkF9vEd+O8UzwX9+YLbytACzYYAySieKNSx2ci
    H/lLtHI5wSPRsCPyPU2Tccma3sx9p1mgoe8s9Zqxog/GhMq10YoX69QKq2CVZIEd
    jz2G3zvQq0q3pPdV7mRt9K1ZOK4RSJmoVUxDd6VVtcw5ei8+XV3JLTx2dEIWCSYh
    FEDbUb7c1vt1NT8zLNdg55PTRhGG17vjpNVYZQIDAQABAoIBAEcHU5mMzwRwwgYO
    rDl/yn9DbP8WMQyoAIS0s07KJoqUCnExUIhaJs1HQ2wIXqhWdnCETC6gbhD0A0uB
    nn9rMV2wdx7qQceVsxHn74itUg7LbK1T+RRIsrpQnrgSxl4EAc5W0fybb7ffFfhE
    64CjMYt5JuQWJ4ys33GAY9L8LhysbI4tQb0sCWZDGPJWE8NuOr+LlSdfFZCA5pYY
    yN/qUdyY/ZLJhKpEllZeXh39SgFtHG43tp9+MlcThWg5zG/A018bEffGSXqRut3F
    ARWWMuk6gZlA1J0cNELw2b87CegrVhUoFuPznpaDKef4hEUo5Opp+5RP0ZrtU3f/
    abgxQOECgYEA0UUjuwzBA8AFfrjA+JQ1FRJTkM20GUtCkK5bWp23eIuTh3vEsfhd
    nNwuVF4mDcUD5wlqSTPs7TnrxdRtqVYGION7ERJJI6sIUEEOnOzyy28JQfVZQ9h1
    S5G7IWxe4m8jWeTr6MZaiaeDafk4sq5NHe1nA7zMSyy7ytfGciKo9F0CgYEA7DJR
    rLo9XHogejPblt2qpjAffyHNx34Vpx0qlaW41oV/3NbNewTOBCWRvi09F7mdXAnF
    iVMZHCd0KUDSnx3nScqyea7mYMLi2RB2yT+agGV8GKOHzg60klCTuqSJrjE3Qscy
    itSUHaz5c10oBn/MNMq7kw11Kk8Yx8L6cps7s6kCgYEAs7rryxRTGUNr9L/8jAHN
    7UEGIFFrImYuz0/QCe12y8Mke7Hi5u7mh3fbGn6ZtC3HAkBl1mUQUVXzlr6xSEQn
    k0uMQMcxpb6Yr0SQploi1HGSw+FSPyDC7JpG25fVjifhdq1Tp2HkFGGYTgXLmjp0
    5QUl+mHGG7JZvwa+2vvFm8kCgYEAxsaqOcUasuMMxgsyeErgvK+vMhzOw1729gbz
    ubEYV2FOdBpKH4exoYfEmdoUmgzZw4Vtut42OZ1ygu1M1CAkb9OoVAO/WhtpMehL
    L57ZdcjyoQGu3tk9Wg155g9m1zQQH6DohjHU3QyfelkhwCZ5QsyDA4TF3+9lGWib
    wSunGNECgYBQXh712M2i1X0Wpuw9st9L3I4QNq09qGzER23qWIqB6kFFiOJg8DFG
    0y/TgzPBDhZQjPgOgG3JkCviZmYdvKg2mzDoypanDblhT3uC8hWFCIiLvDinGzxz
    PlQVQxk9uTcu0lF/GAt86ff9Xda4NSUIiUU9mU9QhlnHZx3her5LuQ==
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-proxy-config
data:
  config.yaml: |-
    version: 4.0

    parallel: 30                      # 漏洞探测的 worker 数量，可以简单理解为同时有 30 个 POC 在运行

    # 全局 http 发包配置
    # 更多解释见 https://docs.xray.cool/#/configration/http
    http:
      proxy: ""                             # 漏洞扫描时使用的代理，如: http://127.0.0.1:8080。 如需设置多个代理，请使用 proxy_rule 或自行创建上层代理
      proxy_rule: []                        # 漏洞扫描使用多个代理的配置规则, 具体请参照文档
      dial_timeout: 5                       # 建立 tcp 连接的超时时间
      read_timeout: 10                      # 读取 http 响应的超时时间，不可太小，否则会影响到 sql 时间盲注的判断
      max_conns_per_host: 50                # 同一 host 最大允许的连接数，可以根据目标主机性能适当增大
      enable_http2: false                   # 是否启用 http2, 开启可以提升部分网站的速度，但目前不稳定有崩溃的风险
      fail_retries: 0                       # 请求失败的重试次数，0 则不重试
      max_redirect: 5                       # 单个请求最大允许的跳转数
      max_resp_body_size: 2097152           # 最大允许的响应大小, 默认 2M
      max_qps: 500                          # 每秒最大请求数
      allow_methods:                        # 允许的请求方法
        - HEAD
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
        - CONNECT
        - TRACE
        - MOVE
        - PROPFIND
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
        # Cookie: key=value

    # 漏洞探测的插件配置
    # 更多解释见 https://docs.xray.cool/#/configration/plugins
    plugins:
      baseline:
        enabled: true
        detect_cors_header_config: true     # 检查 cors 相关配置
        detect_server_error_page: true      # 检查服务器错误信息
        detect_phpinfo: true                # 检查响应是否包含phpinfo
        detect_system_path_leak: false      # 检查响应是否包含系统路径泄露
        detect_outdated_ssl_version: false  # 检查 ssl 版本问题
        detect_http_header_config: false    # 检查 http 安全相关 header 是否配置
        detect_cookie_httponly: false       # 检查 set-cookie 时是否设置 http only
        detect_china_id_card_number: false  # 检查响应是否存在身份证号
        detect_china_phone_number: false    # 检查响应是否存在电话号码
        detect_china_bank_card: false       # 检查响应是否存在银行卡号
        detect_private_ip: false            # 检查响应是否包含内网 ip
      brute-force:
        enabled: true
        username_dictionary: ""             # 自定义用户名字典, 为空将使用内置 TOP10, 配置后将与内置字典**合并**
        password_dictionary: ""             # 自定义密码字典，为空将使用内置 TOP100, 配置后将与内置字典**合并**
      cmd-injection:
        enabled: true
      crlf-injection:
        enabled: true
      dirscan:
        enabled: true
        depth: 1                            # 检测深度，定义 http://t.com/a/ 深度为 1, http://t.com/a 深度为 0
        dictionary: ""                      # 自定义检测字典, 配置后将与内置字典**合并**
        exclude_dir: []                     # 想要排除的内部的扫描category，例如["sensitive/crossdomain","system/key"]
      fastjson:
        enabled: true
      jsonp:
        enabled: true
      path-traversal:
        enabled: true
      phantasm:                             # poc 插件
        enabled: true
        depth: 1
        auto_load_poc: false                # 除内置 poc 外，额外自动加载当前目录以 "poc-" 为文件名前缀的POC文件，等同于在 include_poc 中增加 "./poc-*"
        exclude_poc: []                     # 排除哪些 poc, 支持 glob 语法, 如: "/home/poc/*thinkphp*" 或 "poc-yaml-weblogic*"
        include_poc: []                     # 只使用哪些内置 poc 以及 额外加载哪些本地 poc, 支持 glob 语法, 如："*weblogic*" 或 "/home/poc/*"
          # 也可使用 --poc 仅运行 指定的内置或本地 poc，进行测试。
          # 例如，可使用如下命令，仅运行当前目录下的 poc 且 不运行内置 poc 进行测试：
        # webscan -poc ./poc-* -url http://example.com
        poc_tags:                           # 为POC添加tag, 然后就可以使用--tags来选择启动哪些POC。poc-yaml-test为poc的name，[]中的内容为该POC对应的标签
          poc-yaml-test: ["HW", "ST"]
          poc-yaml-test-1: ["ST"]
      redirect:
        enabled: true
      shiro:
        enabled: true
        cookie_name: rememberMe             # 默认使用哪个 shiro cookie name
        aes_key: []                         # 自定义 shiro key，配置后将与内置 116 key 做合并
        aes_key_file:                       # 自定义存储 shiro key 的文件路径，配置后将自动加载文件中的key
      sqldet:
        enabled: true
        boolean_based_detection: true       # 是否检测布尔盲注
        error_based_detection: true         # 是否检测报错注入
        time_based_detection: false          # 是否检测时间盲注
        use_comment_in_payload: false       # 在 payload 中使用 or, 慎用！可能导致删库！
        detect_sqli_in_cookie: true         # 是否检查在 cookie 中的注入
      ssrf:
        enabled: true
      struts:
        enabled: true
      thinkphp:
        enabled: true
        detect_thinkphp_sqli: true          # 检查 thinkphp 特定语法的 sqli 注入漏洞
      upload:
        enabled: true
      xss:
        enabled: true
        detect_xss_in_cookie: true          # 是否探测入口点在 cookie 中的 xss
        ie_feature: false                   # 是否扫描仅能在 ie 下利用的 xss
      xxe:
        enabled: true

    # 反连平台配置，更多解释见 https://docs.xray.cool/#/configration/reverse
    # 注意: 默认配置为禁用反连平台，这是无法扫描出依赖反连平台的漏洞，这些漏洞包括 fastjson，ssrf 以及 poc 中依赖反连的情况等
    reverse:
      db_file_path: ""                      # 反连平台数据库文件位置, 这是一个 KV 数据库
      token: ""                             # 反连平台认证的 Token, 独立部署时不能为空
      http:
        enabled: false
        listen_ip: 0.0.0.0
        listen_port: ""
        ip_header: ""                       # 在哪个 http header 中取 ip，为空代表从 REMOTE_ADDR 中取
      dns:
        enabled: false
        listen_ip: 0.0.0.0
        domain: ""                          # DNS 域名配置
        is_domain_name_server: false        # 是否修改了域名的 ns 为反连平台，如果是，那 nslookup 等就不需要指定 dns 了
        resolve:                            # DNS 静态解析规则
          - type: A                           # A, AAAA, TXT 三种
            record: localhost
            value: 127.0.0.1
            ttl: 60
      client:
        remote_server: false                # 是否是独立的远程 server，如果是要在下面配置好远程的服务端地址
        http_base_url: ""                   # 默认将根据 ListenIP 和 ListenPort 生成，该地址是存在漏洞的目标反连回来的地址, 当反连平台前面有反代、绑定域名、端口映射时需要自行配置
        dns_server_ip: ""                   # 和 http_base_url 类似，实际用来访问 dns 服务器的地址

    # 被动代理配置
    # 更多解释见 https://docs.xray.cool/#/configration/mitm
    mitm:
      ca_cert: ./ca.crt                     # CA 根证书路径
      ca_key: ./ca.key                      # CA 私钥路径
      basic_auth:                           # 基础认证的用户名密码
        username: ""
        password: ""
      allow_ip_range: []                    # 允许的 ip，可以是 ip 或者 cidr 字符串
      restriction:                          # 代理能够访问的资源限制, 以下各项为空表示不限制
        hostname_allowed: []                # 允许访问的 Hostname，支持格式如 t.com、*.t.com、1.1.1.1、1.1.1.1/24、1.1-4.1.1-8
        hostname_disallowed:                # 不允许访问的 Hostname，支持格式如 t.com、*.t.com、1.1.1.1、1.1.1.1/24、1.1-4.1.1-8
          - '*google*'
          - '*github*'
          - '*.gov.cn'
          - '*.edu.cn'
          - '*chaitin*'
          - '*.xray.cool'
        port_allowed: []                    # 允许访问的端口, 支持的格式如: 80、80-85
        port_disallowed: []                 # 不允许访问的端口, 支持的格式如: 80、80-85
        path_allowed: []                    # 允许访问的路径，支持的格式如: test、*test*
        path_disallowed: []                 # 不允许访问的路径, 支持的格式如: test、*test*
        query_key_allowed: []               # 允许访问的 Query Key，支持的格式如: test、*test*
        query_key_disallowed: []            # 不允许访问的 Query Key, 支持的格式如: test、*test*
        fragment_allowed: []                # 允许访问的 Fragment, 支持的格式如: test、*test*
        fragment_disallowed: []             # 不允许访问的 Fragment, 支持的格式如: test、*test*
        post_key_allowed: []                # 允许访问的 Post Body 中的参数, 支持的格式如: test、*test*
        post_key_disallowed: []             # 不允许访问的 Post Body 中的参数, 支持的格式如: test、*test*
      queue:
        max_length: 3000                    # 队列长度限制, 也可以理解为最大允许多少等待扫描的请求, 请根据内存大小自行调整
      proxy_header:
        via: ""                             # 是否为代理自动添加 Via 头
        x_forwarded: false                  # 是否为代理自动添加 X-Forwarded-{For,Host,Proto,Url} 四个 http 头
      upstream_proxy: "socks5://external-proxy-service:1080"                    # 为 mitm 本身配置独立的代理

    # 基础爬虫配置
    # 更多解释见 https://docs.xray.cool/#/configration/basic-crawler
    basic-crawler:
      max_depth: 0                          # 最大爬取深度， 0 为无限制
      max_count_of_links: 0                 # 本次爬取收集的最大链接数, 0 为无限制
      allow_visit_parent_path: false        # 是否允许爬取父目录, 如果扫描目标为 t.com/a/且该项为 false, 那么就不会爬取 t.com/ 这级的内容
      restriction:                          # 爬虫的允许爬取的资源限制, 为空表示不限制。爬虫会自动添加扫描目标到 Hostname_allowed。
        hostname_allowed: []                # 允许访问的 Hostname，支持格式如 t.com、*.t.com、1.1.1.1、1.1.1.1/24、1.1-4.1.1-8
        hostname_disallowed:                # 不允许访问的 Hostname，支持格式如 t.com、*.t.com、1.1.1.1、1.1.1.1/24、1.1-4.1.1-8
          - '*google*'
          - '*github*'
          - '*.gov.cn'
          - '*.edu.cn'
          - '*chaitin*'
          - '*.xray.cool'
        port_allowed: []                    # 允许访问的端口, 支持的格式如: 80、80-85
        port_disallowed: []                 # 不允许访问的端口, 支持的格式如: 80、80-85
        path_allowed: []                    # 允许访问的路径，支持的格式如: test、*test*
        path_disallowed: []                 # 不允许访问的路径, 支持的格式如: test、*test*
        query_key_allowed: []               # 允许访问的 Query Key，支持的格式如: test、*test*
        query_key_disallowed: []            # 不允许访问的 Query Key, 支持的格式如: test、*test*
        fragment_allowed: []                # 允许访问的 Fragment, 支持的格式如: test、*test*
        fragment_disallowed: []             # 不允许访问的 Fragment, 支持的格式如: test、*test*
        post_key_allowed: []                # 允许访问的 Post Body 中的参数, 支持的格式如: test、*test*
        post_key_disallowed: []             # 不允许访问的 Post Body 中的参数, 支持的格式如: test、*test*
      basic_auth:                           # 基础认证信息
        username: ""
        password: ""

    # 子域名扫描配置，配置解释见 https://docs.xray.cool/#/configration/subdomain
    # 注意：该功能仅限高级版用户使用
    subdomain:
      max_parallel: 500                     # 子域名探测的并发度
      allow_recursion: false                # 是否允许递归探测, 开启后，扫描完一级域名后，会自动将一级的每个域名作为新的目标
      max_recursion_depth: 3                # 最大允许的递归深度, 3 表示 3 级子域名 仅当 allow_recursion 开启时才有意义
      web_only: false                       # 结果中仅显示有 web 应用的, 没有 web 应用的将被丢弃
      ip_only: false                        # 结果中仅展示解析出 IP 的，没有解析成功的将被丢弃
      servers:                              # 子域名扫描过程中使用的 DNS Server
        - 8.8.8.8
        - 8.8.4.4
        - 223.5.5.5
        - 223.6.6.6
        - 114.114.114.114
      sources:
        brute:
          enabled: true
          main_dict: ""                     # 一级大字典路径，为空将使用内置的 TOP 30000 字典
          sub_dict: ""                      # 其他级小字典路径，为空将使用内置过的 TOP 100 字典
        httpfinder:
          enabled: true                     # 使用 http 的一些方式来抓取子域名，包括 js, 配置文件，http header 等等
        dnsfinder:
          enabled: true                     # 使用 dns 的一些错误配置来找寻子域名，如区域传送（zone transfer)
        certspotter:                        # 下面的通过 api 获取的了
          enabled: true
        crt:
          enabled: true
        hackertarget:
          enabled: true
        qianxun:
          enabled: true
        rapiddns:
          enabled: true
        sublist3r:
          enabled: true
        threatminer:
          enabled: true
        virusTotal:
          enabled: true
        alienvault:
          enabled: true
        bufferover:
          enabled: true
        fofa:
          enabled: false
          email: ""
          key: ""
        ip138:
          enabled: true
        myssl:
          enabled: true
        riskiq:
          enabled: false
          user: ""
          key: ""
        quake:
          enabled: false
          key: ""
        baidu:
          enabled: true
          page_limit: 12
        yahoo:
          enabled: true
          page_limit: 12
        sogou:
          enabled: true
          page_limit: 12
        google:
          enabled: true
          page_limit: 12
        bing:
          enabled: true
          page_limit: 12
        ask:
          enabled: true
          page_limit: 12