apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
spec:
  rules:
    - host: proxy.{{.Values.console_domain}}
      http:
        paths:
          - path: / # match all paths that begin with /argo/
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.xray_proxy_service}}   # name of the service
                port:
                  number: {{.Values.xray_proxy_port}}
