---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xray-proxy
    spec:
      containers:
        - name: proxy
          image: leveryd/xray:v2022.11.22
          ports:
            - containerPort: 80
          command: ["/bin/bash", "-c", "/tools/xray webscan --plugins cmd-injection,jsonp,path-traversal,sqldet,xss,xxe,fastjson,shiro,thinkphp --listen 0.0.0.0:80 --webhook-output http://{{.Values.xray_webhook_service}}:{{.Values.xray_webhook_port}}/webhook"]
          resources:
            limits:
              cpu: "3"
            requests:
              cpu: "0.5"
  selector:
    matchLabels:
      app: xray-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.xray_proxy_service}}
spec:
  selector:
    app: xray-proxy
  ports:
    - protocol: TCP
      port: {{.Values.xray_proxy_port}}
      targetPort: 80
