---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xray-proxy
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: proxy
          image: leveryd/xray:v2023.2.21
          ports:
            - containerPort: 80
          command: ["/bin/bash", "-c", "/tools/xray webscan --listen 0.0.0.0:80 --webhook-output http://{{.Values.xray_webhook_service}}:{{.Values.xray_webhook_port}}/webhook --json-output /xray-output/xray.json --html-output /xray-output/xray.html"]
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "3"
          volumeMounts:
            - mountPath: /tools/ca.crt
              subPath: ca.crt
              name: ca-crt
            - mountPath: /tools/ca.key
              subPath: ca.key
              name: ca-key
            - mountPath: /tools/config.yaml
              subPath: config.yaml
              name: config
            - mountPath: /xray-output
              name: xray-output
        - name: logstash
          image: logstash:7.17.3
          command: ["sh", "-c", "logstash --api.enabled false -w 1 --log.level error -f /xray-logstash/logstash.conf"]
          volumeMounts:
            - mountPath: /xray-logstash
              name: xray-output-logstash-config
            - mountPath: /xray-output
              name: xray-output
      volumes:
        - name: ca-crt
          configMap:
            name: xray-proxy-ca
            items:
            - key: ca.crt
              path: ca.crt
        - name: ca-key
          configMap:
            name: xray-proxy-ca
            items:
            - key: ca.key
              path: ca.key
        - name: config
          configMap:
            name: xray-proxy-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: xray-output-logstash-config
          configMap:
            name: xray-output-logstash-config
        - name: xray-output
          emptyDir: {}

  selector:
    matchLabels:
      app: xray-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.xray_proxy_service}}
spec:
  selector:
    app: xray-proxy
  ports:
    - protocol: TCP
      port: {{.Values.xray_proxy_port}}
      targetPort: 80
      nodePort: {{.Values.xray_proxy_nodeport}}
  type: NodePort
