apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level3-domain-ms
spec:
  templates:
    - name: 从API获取兄弟域名-获取子域名-ms扫描-保存结果
      inputs:
        parameters:
          - name: query
            value: 'limit=10000&offset=0&accurate=是'
            description: "console api查询子域名时的条件"
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
          - name: save-subdomain-result
            description: "是否保存子域名结果"
            default: "false"
            enum: ["true", "false"]
          - name: port-range
            description: "端口范围 例如: 1-65535"
            default: "http:80,https:443"
      parallelism: 3
      steps:
        - - name: call-getrootdomain-from-console-api
            arguments:
              parameters:
                - name: query
                  value: {{`"{{inputs.parameters.query}}"`}}
            templateRef:
              name: level1-getrootdomain
              template: from-console-api
        - - name: call-domain-ms
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
                - name: get-subdomain-way
                  value: {{`"{{inputs.parameters.get-subdomain-way}}"`}}
                - name: save-subdomain-result
                  value: {{`"{{inputs.parameters.save-subdomain-result}}"`}}
                - name: port-range
                  value: {{`"{{inputs.parameters.port-range}}"`}}
            templateRef:
              name: level2-domain-ms
              template: 获取子域名-ms扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}