apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level3-nuclei
spec:
  arguments: {}
  templates:
    - name: 从API获取兄弟域名-获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: query
            value: 'limit=10000&offset=0&accurate=是'
            description: "console api查询子域名时的条件"
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
          - name: save-subdomain-result
            default: "false"
            enum: [ "true", "false" ]

      parallelism: 3 # 并发数
      steps:
        - - name: call-getrootdomain-from-console-api
            arguments:
              parameters:
                - name: query
                  value: {{`'{{inputs.parameters.query}}'`}}
            templateRef:
              name: level1-getrootdomain
              template: from-console-api
        - - name: call-subdomain-nuclei-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
                - name: get-subdomain-way
                  value: {{`'{{inputs.parameters.get-subdomain-way}}'`}}
                - name: save-subdomain-result
                  value: {{`'{{inputs.parameters.save-subdomain-result}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}

    - name: 输入域名列表-获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain-list
            description: '待扫描的二级域名列表，比如["a.vulnweb.com", "b.vulnweb.com"]'
            value: '["xxx"]'
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
          - name: save-subdomain-result
            default: "false"
            enum: [ "true", "false" ]
      parallelism: 3
      steps:
        - - name: call-subdomain-nuclei-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
                - name: get-subdomain-way
                  value: {{`'{{inputs.parameters.get-subdomain-way}}'`}}
                - name: save-subdomain-result
                  value: {{`'{{inputs.parameters.save-subdomain-result}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{inputs.parameters.domain-list}}'`}}

---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: everyd-two-hours
spec:
  # run everyd two hour
  schedule: "0 */2 * * *"
  suspend: true
  workflowSpec:
    workflowTemplateRef:
      name: level3-nuclei
    arguments:
      parameters:
        - name: domain-list
          value: '["xxx.com", "yyy.com"]'
        - name: get-subdomain-way
          description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
          default: "subfinder,es,mysql"
        - name: save-subdomain-result
          default: "false"
          enum: [ "true", "false" ]
    entrypoint: 输入域名列表-获取子域名-nuclei扫描-保存结果
