apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: level3-nuclei
spec:
  arguments: {}
  templates:
    - name: 从API获取兄弟域名-获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: query
            value: 'limit=10000&offset=0&accurate=是'
            description: "console api查询子域名时的条件"
          - name: get-subdomain-way
            description: "哪种方式扫描子域名"
            value: all
            enum:
              - all
              - subfinder
              - oneforall
      parallelism: 3 # 并发数
      steps:
        - - name: call-getrootdomain-from-console-api
            arguments:
              parameters:
                - name: query
                  value: {{`'{{inputs.parameters.query}}'`}}
            templateRef:
              name: level1-getrootdomain
              template: from-console-api
        - - name: call-subdomain-nuclei-save-1
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}
            when: {{`'{{inputs.parameters.get-subdomain-way}} == "all" || {{inputs.parameters.get-subdomain-way}} == "subfinder"'`}}
        - - name: call-subdomain-nuclei-save-2
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: oneforall获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}
            when: {{`'{{inputs.parameters.get-subdomain-way}} == "all" || {{inputs.parameters.get-subdomain-way}} == "oneforall"'`}}

    - name: 输入域名列表-获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain-list
            description: '待扫描的二级域名列表，比如["a.vulnweb.com", "b.vulnweb.com"]'
            value: '["xxx"]'
          - name: get-subdomain-way
            description: "哪种方式扫描子域名"
            value: all
            enum:
              - all
              - subfinder
              - oneforall
      parallelism: 3
      steps:
        - - name: call-subdomain-nuclei-save-1
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{inputs.parameters.domain-list}}'`}}
            when: {{`'{{inputs.parameters.get-subdomain-way}} == "all" || {{inputs.parameters.get-subdomain-way}} == "subfinder"'`}}
        - - name: call-subdomain-nuclei-save-2
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: oneforall获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{inputs.parameters.domain-list}}'`}}
            when: {{`'{{inputs.parameters.get-subdomain-way}} == "all" || {{inputs.parameters.get-subdomain-way}} == "oneforall"'`}}

  podGC:
    strategy: OnPodCompletion
  ttlStrategy:
    secondsAfterCompletion: 300
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: everyd-two-hours
spec:
  # run everyd two hour
  schedule: "0 */2 * * *"
  suspend: true
  workflowSpec:
    workflowTemplateRef:
      name: level3-nuclei
    arguments:
      parameters:
        - name: domain-list
          value: '["xxx.com", "yyy.com"]'
        - name: get-subdomain-way
          value: all
          enum:
            - all
            - subfinder
            - oneforall
    entrypoint: 输入域名列表-获取子域名-nuclei扫描-保存结果
