apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: level3-nuclei
spec:
  arguments:
    parameters:
      - name: passive
        description: "passive mode (default: false)"
        default: "false"
        enum:
          - "true"
          - "false"
  templates:
    - name: 从API获取兄弟域名-获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: query
            value: 'limit=10000&offset=0&accurate=是'
            description: "console api查询子域名时的条件"
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
          - name: save-subdomain-result
            default: "false"
            enum: [ "true", "false" ]

      parallelism: 12 # 并发数
      steps:
        - - name: call-getrootdomain-from-console-api
            arguments:
              parameters:
                - name: query
                  value: {{`'{{inputs.parameters.query}}'`}}
            templateRef:
              name: get-asset-level1-sld-domain-from-console
              template: from-console-api
        - - name: call-subdomain-nuclei-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
                - name: get-subdomain-way
                  value: {{`'{{inputs.parameters.get-subdomain-way}}'`}}
                - name: save-subdomain-result
                  value: {{`'{{inputs.parameters.save-subdomain-result}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}

    - name: 输入域名列表-获取子域名-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: domain-list
            description: '待扫描的二级域名列表，比如["a.vulnweb.com", "b.vulnweb.com"]'
            value: '["xxx"]'
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
          - name: save-subdomain-result
            default: "false"
            enum: [ "true", "false" ]
      parallelism: 12
      steps:
        - - name: call-subdomain-nuclei-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
                - name: get-subdomain-way
                  value: {{`'{{inputs.parameters.get-subdomain-way}}'`}}
                - name: save-subdomain-result
                  value: {{`'{{inputs.parameters.save-subdomain-result}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-nuclei扫描-保存结果
            withParam: {{`'{{inputs.parameters.domain-list}}'`}}

    - name: 从API获取兄弟域名-获取子域名-web服务扫描-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: query
            value: 'limit=10000&offset=0&accurate=是'
            description: "console api查询子域名时的条件"
          - name: get-subdomain-way
            description: "哪种方式扫描子域名 subfinder,oneforall,es,mysql"
            default: "subfinder,es,mysql"
          - name: save-subdomain-result
            default: "false"
            enum: [ "true", "false" ]
          - name: port-range
            description: "是否保存子域名结果"
            default: "8000-9000"

      parallelism: 6 # 并发数
      steps:
        - - name: call-getrootdomain-from-console-api
            arguments:
              parameters:
                - name: query
                  value: {{`'{{inputs.parameters.query}}'`}}
            templateRef:
              name: get-asset-level1-sld-domain-from-console
              template: from-console-api
        - - name: call-subdomain-nuclei-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
                - name: get-subdomain-way
                  value: {{`'{{inputs.parameters.get-subdomain-way}}'`}}
                - name: save-subdomain-result
                  value: {{`'{{inputs.parameters.save-subdomain-result}}'`}}
                - name: port-range
                  value: {{`'{{inputs.parameters.port-range}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取子域名-web服务扫描-nuclei扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}

    - name: 从API获取兄弟域名-从ES获取web服务-nuclei扫描-保存结果
      inputs:
        parameters:
          - name: query
            value: 'limit=10000&offset=0&accurate=是'
            description: "console api查询子域名时的条件"

      parallelism: 6 # 并发数
      steps:
        - - name: call-getrootdomain-from-console-api
            arguments:
              parameters:
                - name: query
                  value: {{`'{{inputs.parameters.query}}'`}}
            templateRef:
              name: get-asset-level1-sld-domain-from-console
              template: from-console-api
        - - name: call-subdomain-nuclei-save
            arguments:
              parameters:
                - name: domain
                  value: {{`'{{item}}'`}}
            templateRef:
              name: level2-domain-nuclei
              template: 获取web服务-nuclei扫描-保存结果
            withParam: {{`'{{steps.call-getrootdomain-from-console-api.outputs.result}}'`}}
